// pkg/grpc/inventory/inventory.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: pkg/grpc/inventory/inventory.proto

package inventory

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message containing a list of product IDs.
type GetProductInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductIds    []string               `protobuf:"bytes,1,rep,name=product_ids,json=productIds,proto3" json:"product_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductInfoRequest) Reset() {
	*x = GetProductInfoRequest{}
	mi := &file_pkg_grpc_inventory_inventory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductInfoRequest) ProtoMessage() {}

func (x *GetProductInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_inventory_inventory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductInfoRequest.ProtoReflect.Descriptor instead.
func (*GetProductInfoRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_inventory_inventory_proto_rawDescGZIP(), []int{0}
}

func (x *GetProductInfoRequest) GetProductIds() []string {
	if x != nil {
		return x.ProductIds
	}
	return nil
}

// A message containing the essential info the Order Service needs.
type ProductInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price         float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductInfo) Reset() {
	*x = ProductInfo{}
	mi := &file_pkg_grpc_inventory_inventory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductInfo) ProtoMessage() {}

func (x *ProductInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_inventory_inventory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductInfo.ProtoReflect.Descriptor instead.
func (*ProductInfo) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_inventory_inventory_proto_rawDescGZIP(), []int{1}
}

func (x *ProductInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProductInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductInfo) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

// The response message containing a list of product information.
type GetProductInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*ProductInfo         `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductInfoResponse) Reset() {
	*x = GetProductInfoResponse{}
	mi := &file_pkg_grpc_inventory_inventory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductInfoResponse) ProtoMessage() {}

func (x *GetProductInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_inventory_inventory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductInfoResponse.ProtoReflect.Descriptor instead.
func (*GetProductInfoResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_inventory_inventory_proto_rawDescGZIP(), []int{2}
}

func (x *GetProductInfoResponse) GetProducts() []*ProductInfo {
	if x != nil {
		return x.Products
	}
	return nil
}

var File_pkg_grpc_inventory_inventory_proto protoreflect.FileDescriptor

const file_pkg_grpc_inventory_inventory_proto_rawDesc = "" +
	"\n" +
	"\"pkg/grpc/inventory/inventory.proto\x12\tinventory\"8\n" +
	"\x15GetProductInfoRequest\x12\x1f\n" +
	"\vproduct_ids\x18\x01 \x03(\tR\n" +
	"productIds\"G\n" +
	"\vProductInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05price\"L\n" +
	"\x16GetProductInfoResponse\x122\n" +
	"\bproducts\x18\x01 \x03(\v2\x16.inventory.ProductInfoR\bproducts2k\n" +
	"\x10InventoryService\x12W\n" +
	"\x0eGetProductInfo\x12 .inventory.GetProductInfoRequest\x1a!.inventory.GetProductInfoResponse\"\x00B\x14Z\x12pkg/grpc/inventoryb\x06proto3"

var (
	file_pkg_grpc_inventory_inventory_proto_rawDescOnce sync.Once
	file_pkg_grpc_inventory_inventory_proto_rawDescData []byte
)

func file_pkg_grpc_inventory_inventory_proto_rawDescGZIP() []byte {
	file_pkg_grpc_inventory_inventory_proto_rawDescOnce.Do(func() {
		file_pkg_grpc_inventory_inventory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_grpc_inventory_inventory_proto_rawDesc), len(file_pkg_grpc_inventory_inventory_proto_rawDesc)))
	})
	return file_pkg_grpc_inventory_inventory_proto_rawDescData
}

var file_pkg_grpc_inventory_inventory_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pkg_grpc_inventory_inventory_proto_goTypes = []any{
	(*GetProductInfoRequest)(nil),  // 0: inventory.GetProductInfoRequest
	(*ProductInfo)(nil),            // 1: inventory.ProductInfo
	(*GetProductInfoResponse)(nil), // 2: inventory.GetProductInfoResponse
}
var file_pkg_grpc_inventory_inventory_proto_depIdxs = []int32{
	1, // 0: inventory.GetProductInfoResponse.products:type_name -> inventory.ProductInfo
	0, // 1: inventory.InventoryService.GetProductInfo:input_type -> inventory.GetProductInfoRequest
	2, // 2: inventory.InventoryService.GetProductInfo:output_type -> inventory.GetProductInfoResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_grpc_inventory_inventory_proto_init() }
func file_pkg_grpc_inventory_inventory_proto_init() {
	if File_pkg_grpc_inventory_inventory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_grpc_inventory_inventory_proto_rawDesc), len(file_pkg_grpc_inventory_inventory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_grpc_inventory_inventory_proto_goTypes,
		DependencyIndexes: file_pkg_grpc_inventory_inventory_proto_depIdxs,
		MessageInfos:      file_pkg_grpc_inventory_inventory_proto_msgTypes,
	}.Build()
	File_pkg_grpc_inventory_inventory_proto = out.File
	file_pkg_grpc_inventory_inventory_proto_goTypes = nil
	file_pkg_grpc_inventory_inventory_proto_depIdxs = nil
}
